FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y \
        python3 \
        python3-pip

RUN pip3 install pytest pytest-coverage

COPY . /src/

WORKDIR /src/

RUN pip3 install -e .

CMD python3 -m pytest --cov=kismet_rest --cov-report=term-missing
